version: '3'

services:
  mysqldb:
    image: mysql:latest
    container_name: "mysqldb"
    environment:
      MYSQL_ROOT_PASSWORD: 8tQOfYD7,w7EHHG
      MYSQL_DATABASE: service-app
      MYSQL_USER: service-user
      MYSQL_PASSWORD: fGJnoK9nzQKkM34
    networks:
      - service_app_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init-script.sql
  service-app:
    container_name: "service-app"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/service-app
      SPRING_DATASOURCE_USERNAME: service-user
      SPRING_DATASOURCE_PASSWORD: fGJnoK9nzQKkM34
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - service_app_network

networks:
  service_app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
